theme = "onedark"

[editor]
line-number = "relative" # relative line numbers
true-color = true

[editor.lsp]
display-inlay-hints = true #maybe delete this

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.normal.space]
"ret" = ":lsp-workspace-command"
