theme = "onedark"

[editor]
line-number = "relative" # relative line numbers
middle-click-paste = true
idle-timeout = 0 # instant autocomplete

[editor.lsp]
display-inlay-hints = true
auto-signature-help = false
display-signature-help-docs = false

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.normal]
minus = "file_picker_in_current_buffer_directory"
