theme = "onedark"

[editor]
line-number = "relative" # relative line numbers
bufferline = "multiple" # displaying open buffers (default is never)
rainbow-brackets = true

[editor.lsp]
display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[editor.soft-wrap]
enable = true

[keys.normal]
space.ret = ":lsp-workspace-command"
space.t = "@<space>/<minus><space>\\[<space>\\]" # global search for tasks
C-p = ':lsp-workspace-command tinymist.pinMain "%sh{realpath %{buffer_name}}"' # for typst
