[[language]]
name = "python"
language-servers = ["ruff"]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "markdown"
language-servers = ["markdown-oxide","harper-ls"]

[[language]] 
name = "typst"
language-servers = ["tinymist","harper-ls"]

[language-server.tinymist]
command = "tinymist"
config = { formatterMode = "typstyle" }

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]
