[[language]]
name = "javascript"
roots = ["deno.json", "deno.jsonc", "package.json"]
language-servers = ["deno-lsp"]

[[language]]
name = "markdown"
language-servers = ["markdown-oxide","harper-ls"]

[[language]]
name = "typescript"
roots = ["deno.json", "deno.jsonc", "package.json"]
language-servers = ["deno-lsp"]

[[language]] 
name = "typst"
language-servers = ["tinymist","harper-ls"]
formatter.command = "typstyle"

[language-server.deno-lsp]
command = "deno"
args = ["lsp"]
config.deno.enable = true

[language-server.harper-ls]
command = "harper-ls"
args = ["--stdio"]
