[[language]]
name = "python"
auto-format = true
language-servers = [
  {name = "pyright", except-features = ["diagnostics"]},
  {name = "ruff"}
]

[language-server.ruff]
command = "ruff-lsp"

[[language]]
name = "markdown"
language-servers = ["markdown-oxide","ltex-ls"]

[[language]] 
name = "typst"
language-servers = ["tinymist","ltex-ls"]

[language-server.tinymist]
command = "tinymist"
config = { formatterMode = "typstyle" }
