[[language]]
name = "python"
language-servers = ["pyright"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "markdown"
language-servers = ["marksman", "ltex-ls" ]

[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "^typ(st)?$"
file-types = ["typ"]
roots = []
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
language-servers = ["typst-lsp"]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'$' = '$'

[[grammar]]
name = "typst"
source = { git = "https://github.com/uben0/tree-sitter-typst/", rev = "791cac478226e3e78809b67ff856010bde709594" }

[language-server.ltex-ls]
command = "ltex-ls" 

[language-server.typst-lsp]
command = "typst-lsp" 

