[[language]]
name = "python"
scope = "source.python"
language-servers = ["pylsp"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "typst"
scope = "source.typst"
file-types = ["typ"]
comment-token = "//"
roots = []
language-servers = ["typst-lsp", "ltex-ls"]

[[language]]
name = "markdown"
language-servers = ["marksman", "ltex-ls" ]

[[grammar]]
name = "typst"
source = { git = "https://github.com/frozolotl/tree-sitter-typst", rev = "50915c5fefd6d6d2f48b3e6da7136cb0138b160a"}

[language-server.pylsp]
command = "pylsp"
config = { settings = { args = [], pylsp = { plugins = { ruff = { enabled = true } } } } }

[language-server.ltex-ls]
command = "ltex-ls" 
config.ltex.language = "en-US" 

[language-server.typst-lsp]
command = "typst-lsp" 