[[language]]
name = "python"
auto-format = true
language-servers = [
  {name = "pyright", except-features = ["diagnostics"]},
  {name = "ruff"}
]

[language-server.ruff]
command = "ruff-lsp"

[[language]]
name = "markdown"
language-servers = ["marksman", "ltex-ls" ]

[[language]] 
name = "typst"
formatter.command = "typstfmt"

[language-server.typst-lsp]
command = "typst-lsp"
config = { exportPdf = "never" }
