[[language]]
name = "python"
auto-format = true
language-servers = [
  {name = "pyright", except-features = ["diagnostics"]},
  {name = "ruff"}
]

[language-server.ruff]
command = "ruff-lsp"

[[language]]
name = "markdown"
language-servers = ["marksman", "ltex-ls" ]

[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "^typ(st)?$"
file-types = ["typ"]
roots = []
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
language-servers = ["typst-lsp"]

[language.auto-pairs]
'(' = ')'
'{' = '}'
'[' = ']'
'"' = '"'
'`' = '`'
'$' = '$'

[[grammar]]
name = "typst"
source = { git = "https://github.com/uben0/tree-sitter-typst/", rev = "e35aa22395fdde82bbc4b5700c324ce346dfc9e5" }

[language-server.typst-lsp]
command = "typst-lsp" 
