[[language]]
name = "python"
language-servers = ["ty", "ruff"]

[[language]]
name = "markdown"
language-servers = ["markdown-oxide","harper-ls"]

[[language]] 
name = "typst"
language-servers = ["tinymist","harper-ls"]
formatter.command = "typstyle"

[language-server.tinymist.config]
exportPdf = "onSave" # Default: "never" | "onSave" | "onType"
# outputPath = "$dir/output/$name" #FIXME
# typstExtraArgs = ["main.typ"]
