[[language]]
name = "python"
language-servers = ["pyright"]
formatter = { command = "black", args = ["--quiet", "-"] }
auto-format = true

[[language]]
name = "typst"
scope = "source.typst"
injection-regex = "^typ(st)?$"
file-types = ["typ"]
comment-token = "//"
language-servers = ["typst-lsp", "ltex-ls"]
roots = []

[[language]]
name = "markdown"
language-servers = ["marksman", "ltex-ls" ]

[[grammar]]
name = "typst"
source = { git = "https://github.com/frozolotl/tree-sitter-typst", rev = "04462e79b46e0b502597f97cb7aa8e34653ce237"}

[language-server.ltex-ls]
command = "ltex-ls" 
config.ltex.language = "en-US" 

[language-server.typst-lsp]
command = "typst-lsp" 
