[[language]]
name = "python"
language-servers = ["ruff"]
auto-format = true

[language-server.ruff]
command = "ruff"
args = ["server", "--preview"]

[[language]]
name = "markdown"
language-servers = ["markdown-oxide","ltex-ls"]

[[language]] 
name = "typst"
language-servers = ["tinymist","ltex-ls"]

[language-server.tinymist]
command = "tinymist"
config = { formatterMode = "typstyle" }